version: '3'

services:
  cinema-backend:
    build:
      context: ./
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - cinema-database
      - cinema-session-redis

  cinema-database:
    image: postgres:11-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema-db
    ports: 
     - 5432:5432

  cinema-session-redis:
    image: redis:alpine
    ports:
     - 6379:6379
