spring:
  application:
    name: cinema-backend
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: cinema-security
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  mail:
    host: smtp.gmail.com
    port: 587
    username: cinema.distributed@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
    password: mB=~6_K3[t9M
    default-encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
mail:
  extended:
    no_reply_address: 'no-reply@cinema.com'

routes:
  frontendOrigins:
    - 'https://192.168.0.10'
    - 'https://localhost'
    - 'http://localhost:8080'
  changePasswordTemplate: 'http://localhost:8080/#/change-password?token=%s'
  verification_template: 'http://localhost:8080/#/activate?token=%s'
server:
  port: 8080
